services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3055:3000" # 3055 extern, 3000 in container
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://psusr_openmanus_eelci:password_openmanus@postgres:5432/psdb_openmanus
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - python
    networks:
      - database4life

  python:
    image: python:3.11
    container_name: openmanus-python
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8055 --reload"
    ports:
      - "8055:8055"
    networks:
      - database4life

networks:
  database4life:
    external: true