
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3055:3100"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - database4life
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8055:8055"
    volumes:
      - .:/app
    networks:
      - database4life
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://psusr_openmanus_eelci:password_openmanus@postgres:5432/psdb_openmanus

networks:
  database4life:
    external: true